name: HumHub runtime tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 1'

permissions:
  contents: read

jobs:
  humhub-1-18:
    name: HumHub 1.18
    uses: humhub/module-coding-standards/.github/workflows/codeception-base.yml@main
    with:
      module-id: orgmap
      humhub-branch: v1.18.4
      php: "['8.2', '8.3']"

  humhub-1-19:
    name: HumHub 1.19
    uses: humhub/module-coding-standards/.github/workflows/codeception-base.yml@main
    with:
      module-id: orgmap
      humhub-branch: v1.19.0
      php: "['8.2', '8.3']"
